-- 114_crm_agent_seed.sql — a no-op on purpose. Read this before changing it.
--
-- PRODUCTION ALREADY HAS THIS KEY, SO EDITING THIS FILE CANNOT CHANGE PRODUCTION.
-- db/migrate.mjs skips every key already in schema_migrations, and it keeps no
-- checksum of a file's text. Production holds `migrations/114_crm_agent_seed.sql`
-- with applied_at 2026-08-02 03:40 UTC (read 2026-10-05, SELECT only). That row
-- was never made by running this file: it is the ORIGINAL 114_ghl_agent_seed.sql
-- run, re-keyed under this name by migration 372 on 2026-09-19 (372 renames
-- schema_migrations keys). So on production the agent seed this file describes
-- came from the text that is still in 114_ghl_agent_seed.sql, word for word.
--
-- WHY IT IS EMPTY NOW. This file arrived on main in d61d3677d (2026-10-01) as a
-- copy of 114_ghl_agent_seed.sql with the vendor name stripped out. The strip
-- also deleted the `runtime, runtime_notes, from_name, booking_enabled` lines
-- from most VALUES rows, and turned seven different agent codes into the same
-- 'LEGACY-AGENT'. On an empty database it failed with "VALUES lists must all be
-- the same length", so db/migrate.mjs stopped at 114 and no database could ever
-- be built from this repo (GitHub run 37406614118). Even repaired, it would have
-- seeded rows production does not have (LEGACY-AGENT x7) on top of the real seed.
--
-- SAME END STATE AS PRODUCTION. On an empty database 114_ghl_agent_seed.sql runs
-- right after this file and seeds the eight agents exactly as production's
-- 2026-08-02 run did. This file adding nothing is what production's history
-- amounts to. Changed 2026-10-05 for the M0 step 6 CI fix (mm-c1-ci-fix).

SELECT 1 AS noop_see_114_ghl_agent_seed;
