-- 372_rename_legacy_crm_column_and_keys.sql — a no-op on purpose. Read this
-- before changing it.
--
-- PRODUCTION ALREADY HAS THIS KEY, SO EDITING THIS FILE CANNOT CHANGE PRODUCTION.
-- db/migrate.mjs skips every key already in schema_migrations, and it keeps no
-- checksum of a file's text. Production applied
-- `migrations/372_rename_legacy_crm_column_and_keys.sql` on 2026-09-19 07:38 UTC.
--
-- WHAT IT USED TO DO, AND WHY NONE OF IT BELONGS ON A NEW DATABASE. The old text
-- (see git history, d61d3677d) did three things. Production's state today
-- (read 2026-10-05, SELECT only) shows none of them stuck, and the code agrees:
--
--   1. Re-keyed schema_migrations rows from the old vendor names to the new ones
--      (114, 168, 255). Production then re-applied the old-name files on
--      2026-09-21, so it now holds BOTH names for all three. On an empty
--      database both names are applied before 372 runs, so the rename hit
--      "duplicate key value violates unique constraint schema_migrations_pkey"
--      and stopped every fresh build (GitHub run 37406614118). Nothing to
--      rename there: both rows already exist, exactly as on production.
--   2. Renamed clients.ghl_contact_id to legacy_contact_id. Production still has
--      ghl_contact_id and no legacy_contact_id, and the app reads ghl_contact_id
--      (src/handlers/client-lifecycle.mjs and others). Renaming it on a new
--      database would build a database the code cannot use.
--   3. Moved custom_fields keys ghl_link_* to crm_link_*. Production has 24
--      clients with the ghl_link_* keys and none with crm_link_*, and the app
--      writes ghl_link_missing. Same reason: leave them.
--
-- SAME END STATE AS PRODUCTION: do nothing. Changed 2026-10-05 for the M0 step 6
-- CI fix (mm-c1-ci-fix).

SELECT 1 AS noop_see_header;
