-- 412_repo_outbox.sql — the repo outbox: every app save that must also land in git.
--
-- Spec docs/specs/marketing-machine-2026-10-04.md §6 Step 2 and §2 item 8
-- ("every save goes to the database and the repo"). Columns exactly as the spec
-- names them: id, org_id, op_id, path, mode, content, edit, created_at,
-- claimed_at, claim_id, attempts, committed_sha, committed_at, error.
--
-- HOW A ROW MOVES (code: src/repo/outbox.mjs; diagram: the U05 section of
-- docs/journeys/marketing-dashboard-flow.md):
--   waiting    committed_sha NULL, claimed_at NULL. Written in the SAME
--              transaction as the database change it mirrors, so a rolled-back
--              save leaves no row.
--   claimed    claimed_at + claim_id stamped by one drain (one short transaction,
--              pg_try_advisory_xact_lock — never a session lock: the app talks
--              to the Supabase transaction pooler, where a session lock or a
--              bare SET sticks to a shared backend). A claim is a 10-minute
--              lease; one batch is in flight at a time.
--   committed  committed_sha + committed_at set once the commit is on the branch
--              (or found in an "Outbox: <ids>" trailer in the last 20 commits).
--   error      the reason GitHub (or the edit) refused, kept for the health card.
--              The claim stays and expires after 10 minutes, so it is retried
--              then — never hammered.
--
-- mode 'replace' carries the whole file in `content` (files the machine owns).
-- mode 'edit' carries one edit op in `edit` (shared files: RULES.md, VOICE.md,
-- registry.json, banned-live.json, angles.json), so a retry re-applies the op to
-- the newest copy of the file instead of overwriting someone else's change.
--
-- THE FOLDER ALLOW-LIST LIVES IN CODE (src/repo/allow-list.mjs), checked before
-- the insert and again before the commit. The database adds the traversal guard
-- underneath it: no absolute path, no backslash, no percent-encoding, no empty
-- segment, no segment that starts with a dot (so no "." or "..").
--
-- op_id is the caller's id for the save (for example the request id plus what it
-- writes). One op_id per org: a repeated save cannot queue twice.
--
-- id is a bigint so the commit trailer stays short ("Outbox: 41,42,43").
--
-- Row security: the 402/403 pattern (org_id → orgs, RLS on and forced, an
-- *_app_all policy, the fundhub_app grant inside the pg_roles check) plus the
-- anon/authenticated REVOKE block from 409.

CREATE TABLE IF NOT EXISTS public.repo_outbox (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES orgs(id),
  op_id          text NOT NULL,
  path           text NOT NULL,
  mode           text NOT NULL,
  content        text,
  edit           jsonb,
  created_at     timestamptz NOT NULL DEFAULT now(),
  claimed_at     timestamptz,
  claim_id       text,
  attempts       integer NOT NULL DEFAULT 0,
  committed_sha  text,
  committed_at   timestamptz,
  error          text,

  CONSTRAINT repo_outbox_mode_ck CHECK (mode IN ('replace', 'edit')),
  -- A replace row carries a whole file and no op; an edit row carries one op and
  -- no file. Anything else is a save nobody can apply.
  CONSTRAINT repo_outbox_body_ck CHECK (
    (mode = 'replace' AND content IS NOT NULL AND edit IS NULL)
    OR (mode = 'edit' AND edit IS NOT NULL AND content IS NULL)
  ),
  CONSTRAINT repo_outbox_edit_shape_ck CHECK (
    edit IS NULL OR (jsonb_typeof(edit) = 'object' AND jsonb_typeof(edit -> 'op') = 'string')
  ),
  CONSTRAINT repo_outbox_op_id_ck CHECK (btrim(op_id) <> '' AND length(op_id) <= 200),
  CONSTRAINT repo_outbox_path_ck CHECK (
    length(path) BETWEEN 1 AND 300
    AND path !~ '(^/|\\|%|//|/$|(^|/)\.)'
  ),
  -- A claim is the stamp and the id together, never one without the other.
  CONSTRAINT repo_outbox_claim_pair_ck CHECK ((claimed_at IS NULL) = (claim_id IS NULL)),
  CONSTRAINT repo_outbox_claim_id_ck CHECK (
    claim_id IS NULL OR (btrim(claim_id) <> '' AND length(claim_id) <= 100)
  ),
  CONSTRAINT repo_outbox_attempts_ck CHECK (attempts >= 0),
  CONSTRAINT repo_outbox_committed_pair_ck CHECK ((committed_sha IS NULL) = (committed_at IS NULL)),
  CONSTRAINT repo_outbox_sha_ck CHECK (
    committed_sha IS NULL OR committed_sha ~ '^[0-9a-f]{40}([0-9a-f]{24})?$'
  )
);

-- One op_id per org. src/repo/outbox.mjs enqueueRepoWrite inserts ON CONFLICT
-- against exactly this index and returns the saved row for a repeat.
CREATE UNIQUE INDEX IF NOT EXISTS repo_outbox_org_op_uq
  ON public.repo_outbox (org_id, op_id);

-- The drain's claim and the lease check read only the waiting rows.
CREATE INDEX IF NOT EXISTS repo_outbox_waiting_idx
  ON public.repo_outbox (id)
  WHERE committed_sha IS NULL;

-- "Recent saves to this file" (the rules screen, the health card).
CREATE INDEX IF NOT EXISTS repo_outbox_path_id_idx
  ON public.repo_outbox (path, id DESC);

COMMENT ON TABLE public.repo_outbox IS
  'Repo saves waiting to be committed to GitHub (spec 2026-10-04 §6 Step 2). Written in the same transaction as the database change; drained by src/repo/outbox.mjs drainOutbox with a 10-minute lease.';

ALTER TABLE public.repo_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.repo_outbox FORCE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname = 'public'
       AND tablename  = 'repo_outbox'
       AND policyname = 'repo_outbox_app_all'
  ) THEN
    CREATE POLICY repo_outbox_app_all
      ON public.repo_outbox
      USING (true) WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fundhub_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.repo_outbox TO fundhub_app;
  END IF;
END $$;

-- Supabase's web roles (anon = not logged in, authenticated = any signed-in user of
-- the public API) must never touch this table. The policy above applies to every role
-- and says "true", so the table grants are the only gate: take them away from those
-- two roles. The app does not connect as either one. Skipped where a role is absent.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON public.repo_outbox FROM %I', r);
    END IF;
  END LOOP;
END $$;
