#!/usr/bin/env node
// Bakes the lender names the LenderSlots B-roll spins through into
// src/data/lenders.ts, straight from the bank book:
//   docs/legacy-strong/lenders-legacy-strong.csv (column `name`)
//
// Every name below must match a `name` cell in that file exactly, or the
// script stops and writes nothing. No name is made up, shortened or reworded.
//
// Run from marketing/broll:  node scripts/bake-lenders.mjs

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../../..');
const CSV = path.join(ROOT, 'docs/legacy-strong/lenders-legacy-strong.csv');
const OUT = path.resolve(HERE, '../src/data/lenders.ts');

// The 45 names the reels spin through (45 sits inside "the thirty to fifty
// that fit you"). Picked for clean names: no notes in brackets, no "0%" tags,
// no tip rows, one row per bank, short enough to fit two lines on a reel.
// Big national names are mixed with regional banks so the spin reads real.
const PICK = [
  'Frost Bank',
  'Capital One',
  'Arvest Bank',
  'Bank of Hawaii',
  'Chase',
  'Old National Bank',
  'Prosperity Bank',
  'First Interstate Bank',
  'American Express',
  'Hancock Whitney Bank',
  'Truist',
  'Gate City Bank',
  'Bank of America',
  'Stockman Bank',
  'Southside Bank',
  'Fifth Third',
  'Rockland Trust',
  'KeyBank',
  'Umpqua Bank',
  'Synovus Bank',
  'Wells Fargo',
  'Citi',
  'Bremer Bank',
  'PNC Bank',
  'Atlantic Union Bank',
  'Zions Bank',
  'US Bank',
  'Banner Bank',
  'Huntington Bank',
  'Cadence Bank',
  'First Hawaiian Bank',
  'Regions Bank',
  'Johnson Bank',
  'M&T Bank',
  'Simmons Bank',
  'Associated Bank',
  'Citizens Bank',
  'Intrust Bank',
  'TD Bank',
  'Western Alliance',
  'Comerica Bank',
  'Centier Bank',
  'Valley National Bank',
  'Berkshire Bank',
  'Webster Bank',
];

// Where the three reels land by default: the first three banks on the /roadmap
// sample client's Bank & Lender Match List (the one sample file every piece
// uses), so the reel never contradicts the sample people can open on the page.
// Source: ops/workflows/2026-10-02-roadmap-sample-content/w2-lenders.json.
const SAMPLE_JSON = path.join(ROOT, 'ops/workflows/2026-10-02-roadmap-sample-content/w2-lenders.json');
const LAND = ['Chase', 'American Express', 'Bank of America'];

function splitCsvLine(line) {
  const out = [];
  let cur = '';
  let inQ = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQ) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else inQ = false;
      } else cur += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') {
      out.push(cur);
      cur = '';
    } else cur += c;
  }
  out.push(cur);
  return out;
}

const lines = fs.readFileSync(CSV, 'utf8').split(/\r?\n/).filter((l) => l.trim() !== '');
const header = splitCsvLine(lines[0]);
const nameAt = header.indexOf('name');
if (nameAt < 0) throw new Error('CSV has no `name` column');
const rows = lines.slice(1).map(splitCsvLine);
const inBook = new Set(rows.map((r) => r[nameAt]));

const missing = PICK.filter((n) => !inBook.has(n));
const dupes = PICK.filter((n, i) => PICK.indexOf(n) !== i);
const badLand = LAND.filter((n) => !PICK.includes(n));
if (missing.length || dupes.length || badLand.length) {
  console.error('Refusing to write.', {missing, dupes, badLand});
  process.exit(1);
}
const sampleNames = JSON.parse(fs.readFileSync(SAMPLE_JSON, 'utf8')).banks.map((b) => b.name);
const notInSample = LAND.filter((n) => !sampleNames.includes(n));
if (notInSample.length) {
  console.error('Refusing to write: landing names are not on the /roadmap sample match list', notInSample);
  process.exit(1);
}

const body = `// GENERATED by scripts/bake-lenders.mjs. Do not edit by hand; edit PICK there and re-run.
// Source: docs/legacy-strong/lenders-legacy-strong.csv, column \`name\` (${rows.length} rows, ${inBook.size} distinct names).
// Every name here is copied exactly from that file. Shown only as names
// spinning on a reel: never with an amount, never as an approval.

/** The ${PICK.length} lender names the LenderSlots reels spin through. */
export const LENDER_NAMES: readonly string[] = ${JSON.stringify(PICK, null, 2)};

/** Default landing names, one per reel: the first three banks on the /roadmap sample client's match list. */
export const LENDER_LANDING_DEFAULT: readonly string[] = ${JSON.stringify(LAND)};

export const LENDER_SOURCE = {file: 'docs/legacy-strong/lenders-legacy-strong.csv', rows: ${rows.length}, distinctNames: ${inBook.size}} as const;
`;

fs.mkdirSync(path.dirname(OUT), {recursive: true});
fs.writeFileSync(OUT, body);
console.log(`Wrote ${PICK.length} names (all found in the CSV) to ${path.relative(process.cwd(), OUT)}`);
