#!/usr/bin/env python3
"""
Copy the 40 real approval PNGs into the Remotion project for the ProofWall template.

    python3 marketing/broll/scripts/proof-wall-approvals.py

Source:  marketing/landing-pages/slo/client-wins/deck/win-*.png
         marketing/landing-pages/slo/client-wins/approvals-manifest.json (amount and lender per picture)
Writes:  marketing/broll/public/proof-wall/<id>.png
         marketing/broll/src/templates/proofWallApprovals.ts (generated list the template reads)

Each picture is copied byte for byte, so it stays exactly as it is, except the
few listed in BLUR below. Those still show a client's initials, a sender name,
a tiny profile photo, or a business name / card reference line that the
earlier grey bars missed. Those spots get a heavy blur. Nothing is added to any
picture and no amount is changed.
"""
import json
import shutil
from pathlib import Path

from PIL import Image, ImageFilter

HERE = Path(__file__).resolve().parent
BROLL = HERE.parent
REPO = BROLL.parent.parent
WINS = REPO / "marketing/landing-pages/slo/client-wins"
DECK = WINS / "deck"
MANIFEST = WINS / "approvals-manifest.json"
OUT = BROLL / "public/proof-wall"
TS = BROLL / "src/templates/proofWallApprovals.ts"

# Boxes in the picture's own pixels: (left, top, right, bottom, what is under it).
BLUR = {
    "win-noamount-american-express-p23-1": [(108, 856, 200, 948, "sender initials")],
    "win-7000-citizens": [(96, 1486, 188, 1578, "sender initials")],
    "win-45000-chase": [
        (205, 762, 465, 803, "sender name"),
        (86, 866, 184, 964, "sender initials"),
        (298, 868, 372, 942, "reaction profile photo"),
    ],
    "win-10000-lender": [
        (90, 390, 186, 486, "sender profile picture"),
        (205, 362, 495, 410, "sender name"),
        (205, 780, 495, 826, "sender name"),
        (300, 903, 374, 977, "reaction profile photo"),
    ],
    "win-noamount-enterprise-bank-trust-p08-2": [
        (180, 505, 392, 562, "business name and the line under it"),
        (455, 512, 732, 552, "card reference line"),
    ],
    "win-25000-enterprise-bank-trust": [
        (245, 570, 437, 610, "business name"),
        (495, 575, 752, 613, "card reference line"),
    ],
    "win-noamount-first-citizens-bank-p04-1": [(85, 985, 700, 1042, "banker name and license number under the scribble")],
}


def blur_box(im: Image.Image, box) -> None:
    l, t, r, b = box[:4]
    pad = 24  # blur a little past the box so the edge has nothing sharp to sample
    L, T, R, B = max(0, l - pad), max(0, t - pad), min(im.width, r + pad), min(im.height, b + pad)
    region = im.crop((L, T, R, B))
    for _ in range(3):
        region = region.filter(ImageFilter.GaussianBlur(14))
    im.paste(region.crop((l - L, t - T, r - L, b - T)), (l, t))


def main() -> None:
    manifest = json.loads(MANIFEST.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for m in manifest:
        src = DECK / f"{m['id']}.png"
        dst = OUT / f"{m['id']}.png"
        boxes = BLUR.get(m["id"], [])
        if boxes:
            im = Image.open(src).convert("RGBA")
            for box in boxes:
                blur_box(im, box)
            im.save(dst, optimize=True)
        else:
            shutil.copyfile(src, dst)
        w, h = Image.open(dst).size
        rows.append(
            {
                "id": m["id"],
                "width": w,
                "height": h,
                "amount": m["amount"],
                "lender": m["lender"] or None,
                "kind": m["kind"],
                "blurred": [b[4] for b in boxes],
            }
        )

    lines = [
        "// GENERATED by marketing/broll/scripts/proof-wall-approvals.py. Do not edit by hand.",
        "// The 40 real approvals from marketing/landing-pages/slo/client-wins/approvals-manifest.json,",
        "// copied to public/proof-wall/<id>.png. `amount` and `lender` are the manifest's, read off each",
        "// picture (null = the picture shows none). `blurred` lists what the copy script blurred.",
        "",
        "export type ProofApproval = {",
        "  id: string;",
        "  width: number;",
        "  height: number;",
        "  amount: number | null;",
        "  lender: string | null;",
        "  kind: string;",
        "  blurred: string[];",
        "};",
        "",
        "export const PROOF_APPROVALS: ProofApproval[] = [",
    ]
    for r in rows:
        lines.append(
            "  {"
            f"id: {json.dumps(r['id'])}, width: {r['width']}, height: {r['height']}, "
            f"amount: {json.dumps(r['amount'])}, lender: {json.dumps(r['lender'])}, kind: {json.dumps(r['kind'])}, "
            f"blurred: {json.dumps(r['blurred'])}"
            "},"
        )
    lines += ["];", ""]
    TS.write_text("\n".join(lines))
    print(f"copied {len(rows)} approvals to {OUT.relative_to(REPO)}; blurred spots on {sum(1 for r in rows if r['blurred'])}")


if __name__ == "__main__":
    main()
