// GENERATED by scripts/bake-lenders.mjs. Do not edit by hand; edit PICK there and re-run.
// Source: docs/legacy-strong/lenders-legacy-strong.csv, column `name` (306 rows, 287 distinct names).
// Every name here is copied exactly from that file. Shown only as names
// spinning on a reel: never with an amount, never as an approval.

/** The 45 lender names the LenderSlots reels spin through. */
export const LENDER_NAMES: readonly string[] = [
  "Frost Bank",
  "Capital One",
  "Arvest Bank",
  "Bank of Hawaii",
  "Chase",
  "Old National Bank",
  "Prosperity Bank",
  "First Interstate Bank",
  "American Express",
  "Hancock Whitney Bank",
  "Truist",
  "Gate City Bank",
  "Bank of America",
  "Stockman Bank",
  "Southside Bank",
  "Fifth Third",
  "Rockland Trust",
  "KeyBank",
  "Umpqua Bank",
  "Synovus Bank",
  "Wells Fargo",
  "Citi",
  "Bremer Bank",
  "PNC Bank",
  "Atlantic Union Bank",
  "Zions Bank",
  "US Bank",
  "Banner Bank",
  "Huntington Bank",
  "Cadence Bank",
  "First Hawaiian Bank",
  "Regions Bank",
  "Johnson Bank",
  "M&T Bank",
  "Simmons Bank",
  "Associated Bank",
  "Citizens Bank",
  "Intrust Bank",
  "TD Bank",
  "Western Alliance",
  "Comerica Bank",
  "Centier Bank",
  "Valley National Bank",
  "Berkshire Bank",
  "Webster Bank"
];

/** Default landing names, one per reel: the first three banks on the /roadmap sample client's match list. */
export const LENDER_LANDING_DEFAULT: readonly string[] = ["Chase","American Express","Bank of America"];

export const LENDER_SOURCE = {file: 'docs/legacy-strong/lenders-legacy-strong.csv', rows: 306, distinctNames: 287} as const;
