// GENERATED by scripts/bake-lender-scroll.mjs. Do not edit by hand; edit PICK there and re-run.
// Source: Fundhub CRM table public.lenders (read-only snapshot scripts/data/crm-lenders-with-logos-2026-10-02.json,
// 661 rows that have a logo). Logos are byte-for-byte copies of the CRM's own files in public/assets/lenders/.
// bureaus = the CRM's bureaus_pulled for that bank (every product row combined). products = its lender_table, in words.
// On screen the bureau statuses and products are blurred: real data, hidden.

export type ScrollBank = {
  name: string;
  /** Path for staticFile(), a copy of the CRM logo. */
  logo: string;
  /** The CRM's logo_path for this bank. */
  crmLogoPath: string;
  logoPx: number;
  /** Which bureaus this bank pulls, from the CRM (EX = Experian, EQ = Equifax, TU = TransUnion). */
  bureaus: {EX: boolean; EQ: boolean; TU: boolean};
  products: string;
};

/** The 59 banks LenderMatchScroll scrolls through, in order. */
export const SCROLL_BANKS: readonly ScrollBank[] = [
  {
    "name": "Southside Bank",
    "logo": "lender-logos/southside-bank.png",
    "crmLogoPath": "/assets/lenders/southside-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Chase",
    "logo": "lender-logos/chase.png",
    "crmLogoPath": "/assets/lenders/chase.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch · Personal card · Personal loan"
  },
  {
    "name": "Centier Bank",
    "logo": "lender-logos/centier-bank.png",
    "crmLogoPath": "/assets/lenders/centier-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Bank of America",
    "logo": "lender-logos/bank-of-america.png",
    "crmLogoPath": "/assets/lenders/bank-of-america.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch · Business card, online · Personal card · Personal loan"
  },
  {
    "name": "Emprise Bank",
    "logo": "lender-logos/emprise-bank.png",
    "crmLogoPath": "/assets/lenders/emprise-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Wells Fargo",
    "logo": "lender-logos/wells-fargo.png",
    "crmLogoPath": "/assets/lenders/wells-fargo.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch · Business card, online · Personal card · Personal loan"
  },
  {
    "name": "Hanmi Bank",
    "logo": "lender-logos/hanmi-bank.png",
    "crmLogoPath": "/assets/lenders/hanmi-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Capital One",
    "logo": "lender-logos/capital-one.png",
    "crmLogoPath": "/assets/lenders/capital-one.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, online · Personal card"
  },
  {
    "name": "Northrim Bank",
    "logo": "lender-logos/northrim-bank.png",
    "crmLogoPath": "/assets/lenders/northrim-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Citi",
    "logo": "lender-logos/citi.png",
    "crmLogoPath": "/assets/lenders/citi.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, in branch · Personal loan · Personal card"
  },
  {
    "name": "Oxford Bank",
    "logo": "lender-logos/oxford-bank.png",
    "crmLogoPath": "/assets/lenders/oxford-bank.png",
    "logoPx": 240,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "PNC Bank",
    "logo": "lender-logos/pnc-bank.png",
    "crmLogoPath": "/assets/lenders/pnc-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, in branch · Business card, online"
  },
  {
    "name": "Republic Bank",
    "logo": "lender-logos/republic-bank.png",
    "crmLogoPath": "/assets/lenders/republic-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Fifth Third",
    "logo": "lender-logos/fifth-third.png",
    "crmLogoPath": "/assets/lenders/fifth-third.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "United Community Bank",
    "logo": "lender-logos/united-community-bank.png",
    "crmLogoPath": "/assets/lenders/united-community-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Santander Bank",
    "logo": "lender-logos/santander-bank.png",
    "crmLogoPath": "/assets/lenders/santander-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "First United Bank",
    "logo": "lender-logos/first-united-bank.png",
    "crmLogoPath": "/assets/lenders/first-united-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "M&T Bank",
    "logo": "lender-logos/m-and-t-bank.png",
    "crmLogoPath": "/assets/lenders/m-and-t-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Flagship Bank",
    "logo": "lender-logos/flagship-bank.png",
    "crmLogoPath": "/assets/lenders/flagship-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Huntington Bank",
    "logo": "lender-logos/huntington-bank.png",
    "crmLogoPath": "/assets/lenders/huntington-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Frandsen Bank & Trust",
    "logo": "lender-logos/frandsen-bank-and-trust.png",
    "crmLogoPath": "/assets/lenders/frandsen-bank-and-trust.png",
    "logoPx": 180,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Webster Bank",
    "logo": "lender-logos/webster-bank.png",
    "crmLogoPath": "/assets/lenders/webster-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Gate City Bank",
    "logo": "lender-logos/gate-city-bank.png",
    "crmLogoPath": "/assets/lenders/gate-city-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Synovus Bank",
    "logo": "lender-logos/synovus-bank.png",
    "crmLogoPath": "/assets/lenders/synovus-bank.png",
    "logoPx": 192,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch · Business card, online"
  },
  {
    "name": "HomeTown Bank",
    "logo": "lender-logos/hometown-bank.png",
    "crmLogoPath": "/assets/lenders/hometown-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Old National Bank",
    "logo": "lender-logos/old-national-bank.png",
    "crmLogoPath": "/assets/lenders/old-national-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Mechanics Bank",
    "logo": "lender-logos/mechanics-bank.png",
    "crmLogoPath": "/assets/lenders/mechanics-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "UMB Bank",
    "logo": "lender-logos/umb-bank.png",
    "crmLogoPath": "/assets/lenders/umb-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "MidFirst Bank",
    "logo": "lender-logos/midfirst-bank.png",
    "crmLogoPath": "/assets/lenders/midfirst-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "First Citizens",
    "logo": "lender-logos/first-citizens.png",
    "crmLogoPath": "/assets/lenders/first-citizens.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Newburyport Bank",
    "logo": "lender-logos/newburyport-bank.png",
    "crmLogoPath": "/assets/lenders/newburyport-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Bank OZK",
    "logo": "lender-logos/bank-ozk.png",
    "crmLogoPath": "/assets/lenders/bank-ozk.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Personal card"
  },
  {
    "name": "Park National Bank",
    "logo": "lender-logos/park-national-bank.png",
    "crmLogoPath": "/assets/lenders/park-national-bank.png",
    "logoPx": 255,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Ameris Bank",
    "logo": "lender-logos/ameris-bank.png",
    "crmLogoPath": "/assets/lenders/ameris-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Sharon Bank",
    "logo": "lender-logos/sharon-bank.png",
    "crmLogoPath": "/assets/lenders/sharon-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "BancFirst",
    "logo": "lender-logos/bancfirst.png",
    "crmLogoPath": "/assets/lenders/bancfirst.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Sterling State Bank",
    "logo": "lender-logos/sterling-state-bank.png",
    "crmLogoPath": "/assets/lenders/sterling-state-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Atlantic Union Bank",
    "logo": "lender-logos/atlantic-union-bank.png",
    "crmLogoPath": "/assets/lenders/atlantic-union-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "TriStar Bank",
    "logo": "lender-logos/tristar-bank.png",
    "crmLogoPath": "/assets/lenders/tristar-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Cadence Bank",
    "logo": "lender-logos/cadence-bank.png",
    "crmLogoPath": "/assets/lenders/cadence-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Twin City Bank",
    "logo": "lender-logos/twin-city-bank.png",
    "crmLogoPath": "/assets/lenders/twin-city-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Renasant Bank",
    "logo": "lender-logos/renasant-bank.png",
    "crmLogoPath": "/assets/lenders/renasant-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Virginia National Bank",
    "logo": "lender-logos/virginia-national-bank.png",
    "crmLogoPath": "/assets/lenders/virginia-national-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Trustmark National Bank",
    "logo": "lender-logos/trustmark-national-bank.png",
    "crmLogoPath": "/assets/lenders/trustmark-national-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Bank of Ann Arbor",
    "logo": "lender-logos/bank-of-ann-arbor.png",
    "crmLogoPath": "/assets/lenders/bank-of-ann-arbor.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Valley National Bank",
    "logo": "lender-logos/valley-national-bank.png",
    "crmLogoPath": "/assets/lenders/valley-national-bank.png",
    "logoPx": 144,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "BankIowa",
    "logo": "lender-logos/bankiowa.png",
    "crmLogoPath": "/assets/lenders/bankiowa.png",
    "logoPx": 180,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "Bremer Bank",
    "logo": "lender-logos/bremer-bank.png",
    "crmLogoPath": "/assets/lenders/bremer-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "BankVista",
    "logo": "lender-logos/bankvista.png",
    "crmLogoPath": "/assets/lenders/bankvista.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Eastern Bank",
    "logo": "lender-logos/eastern-bank.png",
    "crmLogoPath": "/assets/lenders/eastern-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, in branch"
  },
  {
    "name": "CCF Bank",
    "logo": "lender-logos/ccf-bank.png",
    "crmLogoPath": "/assets/lenders/ccf-bank.png",
    "logoPx": 192,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, online"
  },
  {
    "name": "Sandy Spring Bank",
    "logo": "lender-logos/sandy-spring-bank.png",
    "crmLogoPath": "/assets/lenders/sandy-spring-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "Camden National Bank",
    "logo": "lender-logos/camden-national-bank.png",
    "crmLogoPath": "/assets/lenders/camden-national-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "WSFS Bank",
    "logo": "lender-logos/wsfs-bank.png",
    "crmLogoPath": "/assets/lenders/wsfs-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": true,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "ConnectOne Bank",
    "logo": "lender-logos/connectone-bank.png",
    "crmLogoPath": "/assets/lenders/connectone-bank.png",
    "logoPx": 256,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "WesBanco",
    "logo": "lender-logos/wesbanco.png",
    "crmLogoPath": "/assets/lenders/wesbanco.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": true,
      "TU": true
    },
    "products": "Business card, in branch"
  },
  {
    "name": "FVC Bank",
    "logo": "lender-logos/fvc-bank.png",
    "crmLogoPath": "/assets/lenders/fvc-bank.png",
    "logoPx": 180,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "FNBO",
    "logo": "lender-logos/fnbo.png",
    "crmLogoPath": "/assets/lenders/fnbo.png",
    "logoPx": 128,
    "bureaus": {
      "EX": true,
      "EQ": false,
      "TU": false
    },
    "products": "Business card, online"
  },
  {
    "name": "1st Source Bank",
    "logo": "lender-logos/1st-source-bank.png",
    "crmLogoPath": "/assets/lenders/1st-source-bank.png",
    "logoPx": 128,
    "bureaus": {
      "EX": false,
      "EQ": false,
      "TU": true
    },
    "products": "Business card, in branch"
  }
];
