// GENERATED by marketing/broll/scripts/proof-wall-approvals.py. Do not edit by hand.
// The 40 real approvals from marketing/landing-pages/slo/client-wins/approvals-manifest.json,
// copied to public/proof-wall/<id>.png. `amount` and `lender` are the manifest's, read off each
// picture (null = the picture shows none). `blurred` lists what the copy script blurred.

export type ProofApproval = {
  id: string;
  width: number;
  height: number;
  amount: number | null;
  lender: string | null;
  kind: string;
  blurred: string[];
};

export const PROOF_APPROVALS: ProofApproval[] = [
  {id: "win-16000-bankunited", width: 1120, height: 1242, amount: 16000, lender: "BankUnited", kind: "email", blurred: []},
  {id: "win-12000-bank-of-america", width: 1120, height: 1020, amount: 12000, lender: "Bank of America", kind: "text", blurred: []},
  {id: "win-45000-fnbo", width: 1120, height: 1910, amount: 45000, lender: "FNBO", kind: "text", blurred: []},
  {id: "win-noamount-chase-p02-1", width: 1120, height: 906, amount: null, lender: "Chase (Ink Business Unlimited card)", kind: "app", blurred: []},
  {id: "win-25000-umpqua-bank", width: 1120, height: 1490, amount: 25000, lender: "Umpqua Bank", kind: "email", blurred: []},
  {id: "win-noamount-first-citizens-bank-p04-1", width: 1120, height: 1338, amount: null, lender: "First Citizens Bank", kind: "email", blurred: ["banker name and license number under the scribble"]},
  {id: "win-7500-pnc", width: 1120, height: 732, amount: 7500, lender: "PNC", kind: "text", blurred: []},
  {id: "win-5000-u-s-bank", width: 1120, height: 1850, amount: 5000, lender: "U.S. Bank", kind: "email", blurred: []},
  {id: "win-noamount-american-express-p05-2", width: 1120, height: 1764, amount: null, lender: "American Express", kind: "email", blurred: []},
  {id: "win-noamount-american-express-and-b-p05-3", width: 1120, height: 662, amount: null, lender: "American Express and Bank of America", kind: "text", blurred: []},
  {id: "win-5000-nihfcu", width: 1120, height: 1060, amount: 5000, lender: "NIHFCU", kind: "text", blurred: []},
  {id: "win-noamount-ibc-bank-p10-1", width: 1120, height: 1742, amount: null, lender: "IBC Bank", kind: "email", blurred: []},
  {id: "win-noamount-u-s-bank-p24-1", width: 1120, height: 1778, amount: null, lender: "U.S. Bank", kind: "email", blurred: []},
  {id: "win-25000-highland-bank", width: 1120, height: 1846, amount: 25000, lender: "Highland Bank", kind: "app", blurred: []},
  {id: "win-noamount-u-s-bank-p08-1", width: 1120, height: 1514, amount: null, lender: "U.S. Bank", kind: "email", blurred: []},
  {id: "win-noamount-enterprise-bank-trust-p08-2", width: 1120, height: 1804, amount: null, lender: "Enterprise Bank & Trust", kind: "letter", blurred: ["business name and the line under it", "card reference line"]},
  {id: "win-noamount-southstate-bank-p08-3", width: 1120, height: 1446, amount: null, lender: "SouthState Bank", kind: "letter", blurred: []},
  {id: "win-12000-bank-of-america-2", width: 1120, height: 1224, amount: 12000, lender: "Bank of America", kind: "text", blurred: []},
  {id: "win-74000-chase", width: 1120, height: 1136, amount: 74000, lender: "Chase", kind: "email", blurred: []},
  {id: "win-noamount-american-express-p23-1", width: 1120, height: 1152, amount: null, lender: "American Express", kind: "text", blurred: ["sender initials"]},
  {id: "win-10000-u-s-bank", width: 1120, height: 1910, amount: 10000, lender: "U.S. Bank", kind: "email", blurred: []},
  {id: "win-25000-enterprise-bank-trust", width: 1120, height: 1910, amount: 25000, lender: "Enterprise Bank & Trust", kind: "letter", blurred: ["business name", "card reference line"]},
  {id: "win-9000-southstate", width: 1120, height: 1866, amount: 9000, lender: "SouthState", kind: "letter", blurred: []},
  {id: "win-16000-bankunited-2", width: 1120, height: 1058, amount: 16000, lender: "BankUnited", kind: "email", blurred: []},
  {id: "win-7000-citizens", width: 1120, height: 1784, amount: 7000, lender: "Citizens", kind: "text", blurred: ["sender initials"]},
  {id: "win-15000-fnbo", width: 1120, height: 1032, amount: 15000, lender: "FNBO", kind: "text", blurred: []},
  {id: "win-noamount-american-express-p27-1", width: 1120, height: 1804, amount: null, lender: "American Express", kind: "email", blurred: []},
  {id: "win-noamount-lender-p27-2", width: 1120, height: 818, amount: null, lender: null, kind: "text", blurred: []},
  {id: "win-14000-chase", width: 1120, height: 816, amount: 14000, lender: "Chase", kind: "text", blurred: []},
  {id: "win-15000-lender", width: 1120, height: 1656, amount: 15000, lender: null, kind: "text", blurred: []},
  {id: "win-20000-truist", width: 1120, height: 1530, amount: 20000, lender: "Truist", kind: "letter", blurred: []},
  {id: "win-10000-lender", width: 1120, height: 1182, amount: 10000, lender: null, kind: "text", blurred: ["sender profile picture", "sender name", "sender name", "reaction profile photo"]},
  {id: "win-noamount-chase-p32-1", width: 1120, height: 1240, amount: null, lender: "Chase", kind: "app", blurred: []},
  {id: "win-10000-lender-2", width: 1120, height: 1308, amount: 10000, lender: null, kind: "text", blurred: []},
  {id: "win-70000-lender", width: 1120, height: 1296, amount: 70000, lender: null, kind: "text", blurred: []},
  {id: "win-25000-lender", width: 1120, height: 1096, amount: 25000, lender: null, kind: "text", blurred: []},
  {id: "win-45000-chase", width: 1120, height: 1378, amount: 45000, lender: "Chase", kind: "text", blurred: ["sender name", "sender initials", "reaction profile photo"]},
  {id: "win-50000-chase", width: 1120, height: 1798, amount: 50000, lender: "Chase", kind: "app", blurred: []},
  {id: "win-noamount-keybank-p37-1", width: 1120, height: 1608, amount: null, lender: "KeyBank", kind: "app", blurred: []},
  {id: "win-50000-keybank", width: 1120, height: 1540, amount: 50000, lender: "KeyBank", kind: "letter", blurred: []},
];
