import React from 'react';
import {AbsoluteFill, Composition, Easing, Img, random, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {
  BILL_ASPECT,
  BackdropStage,
  BrandFrame,
  CARD_EDGE,
  COLORS,
  DEPTH,
  Decor,
  DollarBill,
  DollarCounter,
  Eyebrow,
  FONT_FAMILY,
  FRAME,
  FlatCoin,
  GRID,
  P3D,
  STAGE_CENTER,
  TAG,
  TRACK,
  Wordmark,
  cameraAt,
  cardShadow,
  enter,
  formatDollars,
} from '../brand';
import {FLOOD_APPROVALS, type FloodApproval} from './proofFloodApprovals';

// ProofFlood: a flood of real approvals. Dozens of approval cards fly in out
// of the depth and pile up behind; the headline approvals slam to the front one
// at a time with a flash, a money burst and a big amount chip, then dock as a
// small trophy chip and drop back into the pile. A running total climbs while
// the cards land. It adds only the figures on screen: each card's amount joins
// the total the moment that card lands, so the last frame shows the sum of every
// approval in the clip.
//
// Every picture and figure is real: the crops and their amounts, lenders and
// products come from proofFloodApprovals.ts (generated by
// scripts/proof-flood-approvals.py from deck.json and approvals-manifest.json).
// A card with no lender in its picture shows its product instead. No name or
// face is added. A beat with two approvals (KeyBank) shows both $50,000
// approvals landing and their sum, never one $100,000 approval.
//
// Two formats from one component: "vertical" (1080x1920, ads, no words in the
// top 14% or bottom 35%) and "wide" (3840x2160, the horizontal VSL, words inside
// a 5% title-safe margin). Plain CSS 3D, no WebGL. Render with --gl=angle.

export type ProofFloodFormat = 'vertical' | 'wide';

export type ProofFloodProps = {
  format: ProofFloodFormat;
  /** Approval ids from proofFloodApprovals.ts that make up the flood, in landing order. "all" = all 46, smallest first. */
  approvals: string[] | 'all';
  /**
   * The headline beats, in order. Each beat is one id, or two ids that land together and add up
   * (["t-50k-keybank", "keybank-50k-loc"] = two $50,000 KeyBank approvals, $100,000 KeyBank).
   */
  headline: (string | string[])[];
  /** The running total of the approvals on screen. */
  showTotal: boolean;
  eyebrow: string;
  caption: string;
  /** 120 to 180 frames (4 to 6 seconds). Default 180. */
  durationInFrames?: number;
  showSafeZones?: boolean;
};

export const PROOF_FLOOD_BASE = 180;
/** A frame where the last headline approval is settled in front and the total has landed. */
export const PROOF_FLOOD_HERO = 172;
const MIN_FRAMES = 120;
const MAX_FRAMES = 180;
export const clampProofFlood = (frames: number | undefined): number =>
  Math.min(MAX_FRAMES, Math.max(MIN_FRAMES, Math.round(frames ?? PROOF_FLOOD_BASE)));

export const proofFloodDefaults: ProofFloodProps = {
  format: 'vertical',
  approvals: 'all',
  headline: ['t-74k-chase-ink', ['t-50k-keybank', 'keybank-50k-loc'], 'd-400k-loc', 'd-500k-loc'],
  showTotal: true,
  eyebrow: 'Client approvals',
  caption: 'Real approvals',
};

// ---------------------------------------------------------------------------
// Timing (base frames)

/** First headline slam. The flood is already landing before it. */
const INTRO = 18;
/** Frames a headline card takes to slam in. */
const SLAM = 9;
/** Frames a headline card takes to drop back into the pile (its chip flies to the trophy row). */
const EXIT = 10;
/** Second card of a two-approval beat lands this many frames after the first. */
const PAIR_GAP = 8;
/** Frames a flood card takes to fly in. */
const FLY = 15;

// ---------------------------------------------------------------------------
// Layout per format

type Box = {x: number; y: number; w: number; h: number};
type PileSlot = {x: number; y: number; w: number; z: number; rz: number};

type Geo = {
  W: number;
  H: number;
  /** Size unit: 1 vertical, 2 wide (the wide frame is laid out at about twice the vertical's scale). */
  u: number;
  /** Perspective of the content stage and its origin, frame px. */
  P: number;
  ox: number;
  oy: number;
  /** Where cards may rest. Top and bottom are hard lines; `sides` false lets a card hang off the side edges (vertical), true keeps it inside them (wide, title-safe). */
  pile: {x0: number; x1: number; y0: number; y1: number; w: number; sides: boolean};
  hero1: Box;
  hero2: [Box, Box];
  /** Where headline cards drop into the pile. */
  exitSlots: PileSlot[];
  chip1: number;
  chip2: number;
  chipTotal: number;
  pairTotalY: number;
  eyebrowY: number;
  eyebrowZoom: number;
  /** Trophy chips. */
  pill: {size: number; label: boolean; at: (i: number, n: number) => {x: number; y: number}};
  scrim: {w: number; h: number};
  rain: number;
  gutters: {count: number; bands: [number, number][]};
};

const VERT: Geo = {
  W: FRAME.width,
  H: FRAME.height,
  u: 1,
  P: DEPTH.perspective,
  ox: STAGE_CENTER.x,
  oy: STAGE_CENTER.y,
  // Bottom pulled up from the band edge (1248) so a card's soft shadow ends before BrandFrame's clip.
  pile: {x0: 40, x1: 1040, y0: 376, y1: 1170, w: 280, sides: false},
  hero1: {x: 540, y: 762, w: 580, h: 435},
  hero2: [
    {x: 305, y: 730, w: 410, h: 340},
    {x: 775, y: 730, w: 410, h: 340},
  ],
  exitSlots: [
    {x: 232, y: 610, w: 330, z: -110, rz: -9},
    {x: 848, y: 610, w: 330, z: -118, rz: 8},
    {x: 140, y: 860, w: 330, z: -126, rz: 7},
    {x: 940, y: 860, w: 330, z: -134, rz: -8},
  ],
  chip1: 88,
  chip2: 50,
  chipTotal: 80,
  pairTotalY: 1022,
  eyebrowY: 414,
  eyebrowZoom: 1,
  pill: {
    size: 30,
    label: false,
    at: (i, n) => ({x: 540 + (i - (n - 1) / 2) * 236, y: 470}),
  },
  scrim: {w: 1100, h: 900},
  rain: 14,
  gutters: {count: 6, bands: [[-70, 50], [1030, 1150]]},
};

const WIDE: Geo = {
  W: 3840,
  H: 2160,
  u: 2,
  P: DEPTH.perspective * 2,
  ox: 1920,
  oy: 1080,
  // Pulled in from the 5% title-safe lines (192, 3648, 2052) to leave room for each card's turn and the camera's push-in.
  pile: {x0: 350, x1: 3490, y0: 330, y1: 1890, w: 600, sides: true},
  hero1: {x: 1920, y: 1060, w: 1240, h: 900},
  hero2: [
    {x: 1450, y: 980, w: 840, h: 650},
    {x: 2390, y: 980, w: 840, h: 650},
  ],
  exitSlots: [
    {x: 1040, y: 600, w: 640, z: -220, rz: -8},
    {x: 2820, y: 600, w: 640, z: -236, rz: 7},
    {x: 700, y: 1560, w: 640, z: -252, rz: 6},
    {x: 3140, y: 1560, w: 640, z: -268, rz: -7},
  ],
  chip1: 170,
  chip2: 96,
  chipTotal: 156,
  pairTotalY: 1640,
  eyebrowY: 372,
  eyebrowZoom: 2,
  pill: {
    size: 76,
    label: true,
    at: (i, n) => ({x: 600, y: 1080 + (i - (n - 1) / 2) * 250}),
  },
  scrim: {w: 2400, h: 1700},
  rain: 26,
  gutters: {count: 10, bands: [[-140, 160], [3680, 3980]]},
};

// ---------------------------------------------------------------------------
// Helpers

const clamp01 = (v: number) => Math.max(0, Math.min(1, v));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
const easeOut = (t: number) => 1 - (1 - t) ** 3;
const inOut = Easing.inOut(Easing.cubic);

/** Low-discrepancy points: each new card lands far from the last one. */
const halton = (index: number, base: number): number => {
  let f = 1;
  let r = 0;
  let i = index;
  while (i > 0) {
    f /= base;
    r += f * (i % base);
    i = Math.floor(i / base);
  }
  return r;
};

const BY_ID = new Map(FLOOD_APPROVALS.map((a) => [a.id, a]));

/** "Barclays (JetBlue)" -> "Barclays". */
const lenderName = (a: FloodApproval): string | null => (a.lender ? a.lender.replace(/\s*\(.*\)\s*$/, '') : null);

/** The product without a repeated bank name, lines of credit in sentence case. */
const productName = (a: FloodApproval): string | null => {
  if (!a.product) return null;
  let p = a.product;
  const l = lenderName(a);
  if (l && p.toLowerCase().startsWith(`${l.toLowerCase()} `)) p = p.slice(l.length + 1);
  if (/line of credit/i.test(p)) p = p.charAt(0).toUpperCase() + p.slice(1).toLowerCase();
  return p;
};

/** What a card says next to its amount: the lender, or the product when the picture names no lender. */
const cardLabel = (a: FloodApproval): string => lenderName(a) ?? productName(a) ?? '';

type Dims = {w: number; h: number; iw: number; ih: number; pad: number; fs: number; fh: number; r: number};

/** A card fitted in a box: the whole picture (never cropped), a footer with the amount and the lender. */
const cardDims = (a: FloodApproval, boxW: number, boxH: number): Dims => {
  const s = Math.min(boxW / a.width, boxH / a.height);
  const iw = a.width * s;
  const ih = a.height * s;
  const pad = boxW * 0.03;
  const fs = Math.min(boxW * 0.052, iw * 0.085);
  const fh = fs * 2.05;
  return {w: iw + pad * 2, h: ih + pad + fh, iw, ih, pad, fs, fh, r: boxW * 0.035};
};

/** Where to put an element at depth z so it shows at screen point (sx, sy) at its own size. */
const place = (g: Geo, sx: number, sy: number, z: number) => {
  const k = (g.P - z) / g.P;
  return {x: g.ox + (sx - g.ox) * k, y: g.oy + (sy - g.oy) * k, k};
};

const Check: React.FC<{size: number}> = ({size}) => (
  <svg width={size} height={size} viewBox="0 0 52 52" style={{flex: '0 0 auto', display: 'block'}}>
    <circle cx={26} cy={26} r={26} fill={TAG.ok.fg} />
    <path d="M15 26.5 L22.5 34 L37.5 19" fill="none" stroke="#FFFFFF" strokeWidth={5} strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

// ---------------------------------------------------------------------------
// The approval card

const FloodCard: React.FC<{
  a: FloodApproval;
  d: Dims;
  u: number;
  elevation: number;
  alpha?: number;
  /** 0 to 1: a light sweep across the card (the slam). */
  glint?: number;
  /** Two plates behind the face: the card has real thickness. */
  thick?: boolean;
  /** 0 to 1: the footer (amount and lender). A headline card hides it while its big chip covers that spot. */
  footer?: number;
}> = ({a, d, u, elevation, alpha = 1, glint, thick, footer = 1}) => {
  const bw = Math.max(1.5, d.w / 240) * Math.min(u, 1.5);
  const face: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    borderRadius: d.r,
    boxSizing: 'border-box',
  };
  return (
    <div style={{position: 'relative', width: d.w, height: d.h, ...(thick ? P3D : {})}}>
      {thick ? (
        <>
          <div style={{...face, background: '#DDE0E5', opacity: alpha, transform: `translateZ(${-5 * u}px)`}} />
          <div style={{...face, background: '#C9CDD4', opacity: alpha, transform: `translateZ(${-10 * u}px)`}} />
        </>
      ) : null}
      <div
        style={{
          ...face,
          background: 'linear-gradient(165deg, #FFFFFF 0%, #FFFFFF 60%, #FAFAFB 100%)',
          borderStyle: 'solid',
          borderWidth: bw,
          borderColor: CARD_EDGE.borderColor,
          boxShadow: cardShadow(elevation),
          opacity: alpha,
        }}
      >
        <Img
          src={staticFile(`proof-flood/${a.id}.jpg`)}
          style={{
            position: 'absolute',
            left: d.pad - bw,
            top: d.pad - bw,
            width: d.iw,
            height: d.ih,
            borderRadius: d.r * 0.5,
            boxShadow: `0 0 0 ${Math.max(1, bw * 0.6)}px #E4E4E7`,
            display: 'block',
          }}
        />
        <div
          style={{
            position: 'absolute',
            left: d.pad - bw,
            right: d.pad - bw,
            bottom: 0,
            height: d.fh,
            display: 'flex',
            alignItems: 'center',
            gap: d.fs * 0.38,
            overflow: 'hidden',
            opacity: footer,
          }}
        >
          <Check size={d.fs * 1.12} />
          <span style={{flex: '0 0 auto', fontSize: d.fs, fontWeight: 800, letterSpacing: TRACK.num, color: COLORS.ink, whiteSpace: 'nowrap', fontVariantNumeric: 'tabular-nums'}}>
            {formatDollars(a.amount)}
          </span>
          <span
            style={{
              minWidth: 0,
              fontSize: d.fs * 0.78,
              fontWeight: 600,
              letterSpacing: TRACK.body,
              color: COLORS.gray,
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
            }}
          >
            {cardLabel(a)}
          </span>
        </div>
        {glint !== undefined && glint > 0 && glint < 1 ? (
          <div
            style={{
              ...face,
              background: 'linear-gradient(105deg, rgba(255,255,255,0) 36%, rgba(255,255,255,.75) 50%, rgba(255,255,255,0) 64%)',
              backgroundSize: '300% 100%',
              backgroundPosition: `${100 - 100 * glint}% 0`,
            }}
          />
        ) : null}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Chips

/** The big chip: check, amount, and the lender (or product) beside it. */
const AmountChip: React.FC<{amount: React.ReactNode; line1: string | null; line2: string | null; size: number; u: number}> = ({amount, line1, line2, size, u}) => (
  <div
    style={{
      display: 'inline-flex',
      alignItems: 'center',
      gap: size * 0.24,
      padding: `${size * 0.15}px ${size * 0.42}px ${size * 0.15}px ${size * 0.2}px`,
      borderRadius: 999,
      background: COLORS.white,
      borderStyle: 'solid',
      borderWidth: 2 * u,
      borderColor: CARD_EDGE.borderColor,
      boxShadow: `0 ${4 * u}px 0 -${u}px #DCDCE1, 0 ${18 * u}px ${38 * u}px rgba(10,10,10,.14), 0 0 0 ${size * 0.06}px rgba(62,142,88,.10)`,
      whiteSpace: 'nowrap',
    }}
  >
    <Check size={size * 0.78} />
    <span style={{fontSize: size, fontWeight: 800, letterSpacing: TRACK.num, color: COLORS.ink, lineHeight: 1.06, fontVariantNumeric: 'tabular-nums'}}>{amount}</span>
    {line1 ? (
      <>
        <span style={{flex: '0 0 auto', width: 2 * u, height: size * 0.66, background: COLORS.line}} />
        <span style={{display: 'flex', flexDirection: 'column', lineHeight: 1.08}}>
          <span style={{fontSize: size * 0.4, fontWeight: 700, letterSpacing: TRACK.body, color: COLORS.ink2}}>{line1}</span>
          {line2 ? <span style={{fontSize: size * 0.29, fontWeight: 600, letterSpacing: TRACK.body, color: COLORS.gray}}>{line2}</span> : null}
        </span>
      </>
    ) : null}
  </div>
);

/** A docked trophy chip (a headline approval that already had its moment). */
const Pill: React.FC<{amount: number; label: string | null; size: number; u: number}> = ({amount, label, size, u}) => (
  <div
    style={{
      display: 'inline-flex',
      alignItems: 'center',
      gap: size * 0.3,
      padding: `${size * 0.26}px ${size * 0.5}px ${size * 0.26}px ${size * 0.3}px`,
      borderRadius: 999,
      background: COLORS.white,
      borderStyle: 'solid',
      borderWidth: 2 * u,
      borderColor: CARD_EDGE.borderColor,
      boxShadow: `0 ${3 * u}px 0 -${u}px #DCDCE1, 0 ${10 * u}px ${22 * u}px rgba(10,10,10,.10)`,
      whiteSpace: 'nowrap',
    }}
  >
    <Check size={size * 0.9} />
    <span style={{display: 'flex', flexDirection: 'column', lineHeight: 1.08}}>
      <span style={{fontSize: size, fontWeight: 800, letterSpacing: TRACK.num, color: COLORS.ink, fontVariantNumeric: 'tabular-nums'}}>{formatDollars(amount)}</span>
      {label ? <span style={{fontSize: size * 0.5, fontWeight: 600, letterSpacing: TRACK.body, color: COLORS.gray}}>{label}</span> : null}
    </span>
  </div>
);

// ---------------------------------------------------------------------------
// Money (decoration only; dropped by a checkTextOnly render)

type Piece = {sx: number; sy: number; z: number; w: number; rx: number; ry: number; rz: number; a: number; coin: boolean};

const MoneyPieces: React.FC<{pieces: Piece[]; P: number; ox: number; oy: number; band?: [number, number]}> = ({pieces, P, ox, oy, band}) => (
  <>
    {pieces.map((p, i) => {
      // Inside the clipped text band, money fades out before it reaches the band's edge (never a hard cut).
      const edge = band ? clamp01((p.sy - band[0] - 40) / 90) * clamp01((band[1] - p.sy - 40) / 90) : 1;
      const alpha = p.a * edge;
      if (alpha < 0.01) return null;
      const k = (P - p.z) / P;
      const X = ox + (p.sx - ox) * k;
      const Y = oy + (p.sy - oy) * k;
      const cw = p.coin ? p.w * 0.42 : p.w;
      const h = p.coin ? cw : p.w / BILL_ASPECT;
      return (
        <div
          key={i}
          style={{
            position: 'absolute',
            left: X - cw / 2,
            top: Y - h / 2,
            width: cw,
            height: h,
            opacity: alpha,
            transform: `translateZ(${p.z}px) rotateZ(${p.rz}deg) rotateX(${p.rx}deg) rotateY(${p.ry}deg)`,
          }}
        >
          {p.coin ? <FlatCoin size={cw} /> : <DollarBill width={p.w} detail="simple" />}
        </div>
      );
    })}
  </>
);

/** Bills and coins falling the whole clip, far behind the cards. */
const rainPieces = (g: Geo, f: number, seed: string, count: number, zRange: [number, number], alpha: number, bands?: [number, number][]): Piece[] => {
  const out: Piece[] = [];
  for (let i = 0; i < count; i++) {
    const r = (k: number) => random(`${seed}-${i}-${k}`);
    const near = r(1);
    const z = (zRange[0] + (zRange[1] - zRange[0]) * near) * g.u;
    const w = (130 + 110 * r(2)) * g.u;
    const span = g.H + 500 * g.u;
    const v = (3.2 + 3.4 * r(3)) * g.u;
    const p = (((r(4) * span + f * v) % span) + span) % span;
    const band = bands ? bands[i % bands.length] : ([0, g.W] as [number, number]);
    const phase = r(5) * Math.PI * 2;
    out.push({
      sx: band[0] + (band[1] - band[0]) * r(6) + Math.sin(f * 0.05 + phase) * 24 * g.u,
      sy: -250 * g.u + p,
      z,
      w,
      rz: -35 + 70 * r(7) + Math.sin(f * 0.06 + phase) * 14,
      rx: Math.sin(f * 0.08 + phase * 1.3) * 36,
      ry: Math.cos(f * 0.05 + phase) * 28,
      a: alpha * (0.55 + 0.45 * near),
      coin: r(8) < 0.3,
    });
  }
  return out;
};

/** A burst of bills and coins flying out from behind a slammed card toward the camera. */
const burstPieces = (g: Geo, f: number, at: number, cx: number, cy: number, w: number, h: number, seed: string, count: number, power: number): Piece[] => {
  const age = f - at + 1;
  if (age <= 0 || age > 30) return [];
  const out: Piece[] = [];
  for (let i = 0; i < count; i++) {
    const r = (k: number) => random(`${seed}-${i}-${k}`);
    // Out to the left and right (never straight up through the wordmark or down over the chip).
    const ang = (i % 2 === 0 ? 0 : Math.PI) + (r(1) - 0.5) * (Math.PI * 0.55);
    const dirX = Math.cos(ang);
    const dirY = Math.sin(ang) * 0.7;
    const v = (13 + 15 * r(2)) * g.u * power;
    const life = 20 + 8 * r(3);
    const t = age / life;
    if (t >= 1) continue;
    const zv = (8 + 10 * r(4)) * g.u;
    out.push({
      sx: cx + dirX * (w * 0.42 + v * age),
      sy: cy + dirY * (h * 0.42 + v * age) + 0.35 * g.u * age * age,
      // Capped just behind the card's face, so money never crosses in front of the approval.
      z: Math.min(-40 * g.u + zv * age, 18 * g.u),
      w: (110 + 80 * r(5)) * g.u,
      rz: -40 + 80 * r(6) + age * (r(7) - 0.5) * 18,
      rx: age * (8 + 10 * r(8)),
      ry: age * (r(9) - 0.5) * 22,
      a: Math.min(1, age / 2) * (1 - clamp01((t - 0.55) / 0.45)) * 0.95,
      coin: r(10) < 0.35,
    });
  }
  return out;
};

/** Bills and coins hanging and turning over the pile, slowly rising. */
const driftPieces = (g: Geo, f: number, seed: string, count: number, top: number, bottom: number): Piece[] => {
  const out: Piece[] = [];
  const span = bottom - top;
  for (let i = 0; i < count; i++) {
    const r = (k: number) => random(`${seed}-${i}-${k}`);
    const phase = r(5) * Math.PI * 2;
    const y = top + ((((r(4) * span - f * (1.2 + 1.6 * r(3)) * g.u) % span) + span) % span);
    out.push({
      sx: g.W * (0.04 + 0.92 * r(6)) + Math.sin(f * 0.04 + phase) * 30 * g.u,
      sy: y,
      z: (-200 + 100 * r(1)) * g.u,
      w: (120 + 80 * r(2)) * g.u,
      rz: -40 + 80 * r(7) + Math.sin(f * 0.05 + phase) * 10,
      rx: 18 + Math.sin(f * 0.06 + phase) * 22,
      ry: Math.cos(f * 0.045 + phase) * 26,
      a: 0.75,
      coin: r(8) < 0.3,
    });
  }
  return out;
};

// ---------------------------------------------------------------------------
// The plan: which cards, where they rest, when they land

type FloodCardPlan = {a: FloodApproval; land: number; x: number; y: number; w: number; h: number; z: number; rx: number; ry: number; rz: number; from: {dx: number; dy: number; rx: number; ry: number; rz: number}};
type Beat = {cards: FloodApproval[]; s: number; exitAt: number; last: boolean; index: number};

const buildPlan = (props: ProofFloodProps, g: Geo) => {
  const beats: Beat[] = [];
  const raw = props.headline
    .map((h) => (Array.isArray(h) ? h : [h]).map((id) => BY_ID.get(id)).filter((a): a is FloodApproval => Boolean(a)).slice(0, 2))
    .filter((b) => b.length > 0);
  const weights = raw.map((b) => (b.length > 1 ? 1.45 : 1));
  const sum = weights.reduce((x, y) => x + y, 0) || 1;
  let s = INTRO;
  raw.forEach((cards, i) => {
    const span = ((PROOF_FLOOD_BASE - INTRO) * weights[i]) / sum;
    beats.push({cards, s, exitAt: s + span - SLAM, last: i === raw.length - 1, index: i});
    s += span;
  });
  const heroIds = new Set(beats.flatMap((b) => b.cards.map((a) => a.id)));
  const pool = props.approvals === 'all' ? FLOOD_APPROVALS : props.approvals.map((id) => BY_ID.get(id)).filter((a): a is FloodApproval => Boolean(a));
  const flood = pool.filter((a) => !heroIds.has(a.id));
  const lastSlam = beats.length > 0 ? beats[beats.length - 1].s : PROOF_FLOOD_BASE - 20;
  const n = flood.length;
  const cards: FloodCardPlan[] = flood.map((a, j) => {
    const r = (k: number) => random(`proof-flood-${a.id}-${k}`);
    const t = n > 1 ? j / (n - 1) : 0;
    const land = 3 + (lastSlam - 6 - 3) * t ** 1.1;
    const boost = 1 + 0.32 * clamp01(Math.log10(a.amount / 40000));
    const sw = g.pile.w * (0.88 + 0.2 * r(1)) * boost;
    const d = cardDims(a, sw, sw * 0.78);
    const hx = halton(j + 3, 2);
    const hy = halton(j + 3, 3);
    const inset = g.pile.sides ? d.w * 0.6 : d.w * 0.15;
    const x = Math.max(g.pile.x0 + inset, Math.min(g.pile.x1 - inset, g.pile.x0 + hx * (g.pile.x1 - g.pile.x0)));
    const yMin = g.pile.y0 + d.h / 2 + 6 * g.u;
    const yMax = g.pile.y1 - d.h / 2 - 14 * g.u;
    const y = yMin + hy * Math.max(0, yMax - yMin);
    const z = g.u * (-1380 + 1180 * t);
    const side = x < g.ox ? -1 : 1;
    return {
      a,
      land,
      x,
      y,
      w: sw,
      h: sw * 0.78,
      z,
      rx: -4 + 8 * r(2),
      ry: -5 + 10 * r(3),
      rz: -13 + 26 * r(4),
      from: {
        dx: side * (0.25 + 0.3 * r(5)),
        dy: -0.15 + 0.3 * r(6),
        rx: 40 + 30 * r(7),
        ry: side * (25 + 30 * r(8)),
        rz: (r(9) < 0.5 ? -1 : 1) * (45 + 50 * r(10)),
      },
    };
  });
  const total = cards.reduce((x, c) => x + c.a.amount, 0) + beats.reduce((x, b) => x + b.cards.reduce((y, a) => y + a.amount, 0), 0);
  return {beats, cards, total};
};

// ---------------------------------------------------------------------------
// The scene

const ProofFloodScene: React.FC<ProofFloodProps & {g: Geo; f: number; fps: number; plan: ReturnType<typeof buildPlan>}> = ({g, f, fps, plan, eyebrow, caption, showTotal}) => {
  const {u} = g;
  const wide = g.u > 1;
  const {beats, cards, total: FINAL} = plan;

  // Slams, for the flash, shake and bursts.
  const slams = beats.flatMap((b) => b.cards.map((_a, k) => ({at: b.s + k * PAIR_GAP, beat: b, k, last: b.last && k === b.cards.length - 1})));

  // Camera: the shared slow drift, a push-in, and a short shake on each slam.
  let shx = 0;
  let shy = 0;
  for (const sl of slams) {
    const age = f - sl.at;
    if (age >= 0 && age < 12) {
      const damp = (1 - age / 12) ** 2 * (sl.last ? 1.4 : 1);
      shx += Math.sin(age * 2.3) * 9 * u * damp;
      shy += Math.cos(age * 2.9) * 7 * u * damp;
    }
  }
  const cam = cameraAt(f / PROOF_FLOOD_BASE, 0.7);
  const camT = `translate3d(${shx}px, ${shy}px, ${(cam.z + 40 * (f / PROOF_FLOOD_BASE)) * u}px) rotateX(${cam.rx}deg) rotateY(${cam.ry}deg)`;

  // Running total: a card's amount joins as it lands.
  const landed = (t: number) => clamp01((f - (t - 3)) / 3);
  let running = 0;
  for (const c of cards) running += c.a.amount * landed(c.land);
  for (const sl of slams) running += sl.beat.cards[sl.k].amount * landed(sl.at);
  const y = FINAL > 0 ? Math.min(1, running / FINAL) : 0;

  // ---- pile
  const pile: React.ReactNode[] = [];
  for (const c of cards) {
    const p = clamp01((f - (c.land - FLY)) / FLY);
    if (p <= 0) continue;
    const e = easeOut(p);
    const rest = place(g, c.x, c.y, c.z);
    const d = cardDims(c.a, c.w * rest.k, c.h * rest.k);
    const z0 = c.z - 2300 * u;
    const X = lerp(g.ox + (rest.x - g.ox) * 1.3 + c.from.dx * g.W * 0.4, rest.x, e);
    const Y = lerp(g.oy + (rest.y - g.oy) * 1.2 + c.from.dy * g.H * 0.2, rest.y, e);
    const z = lerp(z0, c.z, e);
    pile.push(
      <div
        key={c.a.id}
        style={{
          position: 'absolute',
          left: X - d.w / 2,
          top: Y - d.h / 2,
          transform: `translateZ(${z}px) rotateX(${lerp(c.from.rx, c.rx, e)}deg) rotateY(${lerp(c.from.ry, c.ry, e)}deg) rotateZ(${lerp(c.rz + c.from.rz, c.rz, e)}deg)`,
        }}
      >
        <FloodCard a={c.a} d={d} u={u} elevation={lerp(2.2, 0.75, e) * u * (c.w / g.pile.w)} alpha={clamp01(p / 0.22)} />
      </div>,
    );
  }

  // ---- headline cards, chips, trophy pills
  const heroes: React.ReactNode[] = [];
  const chips: React.ReactNode[] = [];
  const pills: React.ReactNode[] = [];
  const docked = beats.filter((b) => !b.last);
  let scrimX = g.hero1.x;
  let scrimY = g.hero1.y;
  let heroCount = 0;
  for (const b of beats) {
    const pair = b.cards.length > 1;
    const boxes = pair ? g.hero2 : [g.hero1];
    const firstHero = heroCount;
    heroCount += b.cards.length;
    const q = b.last ? 0 : inOut(clamp01((f - b.exitAt) / EXIT));
    const restDims = b.cards.map((a, k) => cardDims(a, boxes[k].w, boxes[k].h));
    if (f >= b.s - SLAM && (b.last || f < b.exitAt + EXIT)) {
      scrimX = pair ? (boxes[0].x + boxes[1].x) / 2 : boxes[0].x;
      scrimY = pair ? boxes[0].y + 60 * u : boxes[0].y;
    }
    b.cards.forEach((a, k) => {
      const at = b.s + k * PAIR_GAP;
      const p = clamp01((f - (at - SLAM)) / SLAM);
      if (p <= 0) return;
      const box = boxes[k];
      const slot = g.exitSlots[(firstHero + k) % g.exitSlots.length];
      const e = p ** 1.7;
      const zRest = 40 * u;
      const dir = k === 0 ? (pair ? -1 : (b.index % 2 === 0 ? -1 : 1)) : 1;
      let sx = box.x;
      let sy = box.y;
      let z = lerp(900 * u, zRest, e);
      let bw = box.w;
      let bh = box.h;
      let rx = lerp(24, 0.6 * Math.sin(f * 0.11 + k), e);
      let ry = lerp(dir * 16, 0, e);
      let rz = lerp(dir * -9, dir * 0.8, e);
      if (q > 0) {
        sx = lerp(box.x, slot.x, q);
        sy = lerp(box.y, slot.y, q);
        z = lerp(zRest, slot.z * u, q);
        const sc = lerp(1, slot.w / box.w, q);
        bw = box.w * sc;
        bh = box.h * sc;
        rx = lerp(rx, 3, q);
        ry = lerp(ry, -dir * 5, q);
        rz = lerp(rz, slot.rz, q);
      }
      // During the slam the card keeps its resting size in 3D, so it looks huge close to the camera.
      const anchor = place(g, sx, sy, q > 0 ? z : zRest);
      const k3 = q > 0 ? (g.P - z) / g.P : (g.P - zRest) / g.P;
      const d = cardDims(a, bw * k3, bh * k3);
      heroes.push(
        <div
          key={`hero-${a.id}`}
          style={{
            position: 'absolute',
            left: anchor.x - d.w / 2,
            top: anchor.y - d.h / 2,
            ...P3D,
            transform: `translateZ(${z}px) rotateX(${rx}deg) rotateY(${ry}deg) rotateZ(${rz}deg)`,
          }}
        >
          <FloodCard a={a} d={d} u={u} elevation={lerp(lerp(1.3, 1.7, e), 0.9, q) * u} alpha={clamp01(p / 0.3)} glint={clamp01((f - at) / 14)} thick footer={1 - enter(f, fps, at + 1, 8) * (1 - q)} />
        </div>,
      );
    });

    // The chips for this beat (screen positions, flat, in front).
    const chipZ = 120 * u;
    const pillAt = docked.indexOf(b) >= 0 ? g.pill.at(docked.indexOf(b), docked.length) : null;
    const flyOut = b.last ? 0 : clamp01((f - b.exitAt) / EXIT);
    const fly = inOut(flyOut);
    const flatAt = (sx: number, sy: number, scale: number, alpha: number, key: string, node: React.ReactNode) => {
      const pl = place(g, sx, sy, chipZ);
      chips.push(
        <div
          key={key}
          style={{
            position: 'absolute',
            left: pl.x,
            top: pl.y,
            opacity: alpha,
            transform: `translate(-50%, -50%) translateZ(${chipZ}px) scale(${pl.k * scale})`,
          }}
        >
          {node}
        </div>,
      );
    };
    const total = b.cards.reduce((x, a) => x + a.amount, 0);
    const lenders = Array.from(new Set(b.cards.map((a) => lenderName(a) ?? '')));
    const common = lenders.length === 1 && lenders[0] ? lenders[0] : null;
    if (!pair) {
      const a = b.cards[0];
      const pop = enter(f, fps, b.s + 1, 8);
      if (pop > 0.01 && flyOut < 1) {
        const cy = boxes[0].y + restDims[0].h / 2 + g.chip1 * 0.3;
        const cx = boxes[0].x;
        const tx = pillAt ? lerp(cx, pillAt.x, fly) : cx;
        const ty = pillAt ? lerp(cy, pillAt.y, fly) : cy;
        flatAt(
          tx,
          ty,
          lerp(1.22 - 0.22 * pop, 0.36, fly),
          pop * (1 - clamp01((flyOut - 0.55) / 0.45)),
          `chip-${b.index}`,
          <AmountChip amount={formatDollars(a.amount)} line1={lenderName(a) ?? productName(a)} line2={lenderName(a) ? productName(a) : null} size={g.chip1} u={u} />,
        );
      }
    } else {
      b.cards.forEach((a, k) => {
        const pop = enter(f, fps, b.s + k * PAIR_GAP + 1, 8);
        if (pop < 0.01 || flyOut >= 1) return;
        flatAt(
          boxes[k].x,
          boxes[k].y + restDims[k].h / 2 - 8 * u,
          (1.2 - 0.2 * pop) * (1 - 0.3 * fly),
          pop * (1 - clamp01(flyOut / 0.5)),
          `chip-${b.index}-${k}`,
          <AmountChip amount={formatDollars(a.amount)} line1={lenderName(a) ?? productName(a)} line2={lenderName(a) ? productName(a) : null} size={g.chip2} u={u} />,
        );
      });
      // "+" between the two cards.
      const plus = enter(f, fps, b.s + PAIR_GAP + 2, 8);
      if (plus > 0.01 && flyOut < 1) {
        const ps = g.chip2 * 1.1;
        flatAt(
          (boxes[0].x + boxes[1].x) / 2,
          boxes[0].y,
          0.6 + 0.4 * plus,
          plus * (1 - clamp01(flyOut / 0.5)),
          `plus-${b.index}`,
          <div
            style={{
              width: ps,
              height: ps,
              borderRadius: '50%',
              background: COLORS.accent,
              color: COLORS.white,
              fontSize: ps * 0.78,
              fontWeight: 800,
              lineHeight: `${ps * 0.92}px`,
              textAlign: 'center',
              boxShadow: `0 ${8 * u}px ${20 * u}px rgba(61,134,240,.35)`,
            }}
          >
            +
          </div>,
        );
      }
      // The sum: counts from the first card's amount up to the total once the second lands.
      const sumAt = b.s + PAIR_GAP + 4;
      const pop = enter(f, fps, sumAt, 9);
      if (pop > 0.01 && flyOut < 1) {
        const cx = (boxes[0].x + boxes[1].x) / 2;
        const cy = g.pairTotalY;
        const tx = pillAt ? lerp(cx, pillAt.x, fly) : cx;
        const ty = pillAt ? lerp(cy, pillAt.y, fly) : cy;
        flatAt(
          tx,
          ty,
          lerp(1.22 - 0.22 * pop, 0.4, fly),
          pop * (1 - clamp01((flyOut - 0.55) / 0.45)),
          `sum-${b.index}`,
          <AmountChip
            amount={<DollarCounter value={total} from={b.cards[0].amount} f={f} start={sumAt} end={sumAt + 9} size={g.chipTotal} color={COLORS.ink} />}
            line1={common ? `${common} total` : 'Total'}
            line2={`${b.cards.length} approvals`}
            size={g.chipTotal}
            u={u}
          />,
        );
      }
    }
    // The trophy pill once the chip has flown up.
    if (pillAt) {
      const pp = enter(f, fps, b.exitAt + EXIT * 0.55, 8);
      if (pp > 0.01) {
        const label = g.pill.label ? (pair ? common : (lenderName(b.cards[0]) ?? productName(b.cards[0]))) : null;
        const pl = place(g, pillAt.x, pillAt.y, chipZ);
        pills.push(
          <div
            key={`pill-${b.index}`}
            style={{
              position: 'absolute',
              left: pl.x,
              top: pl.y,
              opacity: pp,
              transform: `translate(-50%, -50%) translateZ(${chipZ}px) scale(${pl.k * (0.86 + 0.14 * pp)})`,
            }}
          >
            <Pill amount={total} label={label} size={g.pill.size} u={u} />
          </div>,
        );
      }
    }
  }

  // ---- the veil behind the headline card, so it reads over the pile
  const firstSlam = beats.length > 0 ? beats[0].s : PROOF_FLOOD_BASE;
  const scrimOn = clamp01((f - (firstSlam - 4)) / 8);
  const scrimPl = place(g, scrimX, scrimY, -80 * u);
  const scrim =
    scrimOn > 0.005 ? (
      <div
        key="scrim"
        style={{
          position: 'absolute',
          left: scrimPl.x - (g.scrim.w * scrimPl.k) / 2,
          top: scrimPl.y - (g.scrim.h * scrimPl.k) / 2,
          width: g.scrim.w * scrimPl.k,
          height: g.scrim.h * scrimPl.k,
          borderRadius: '50%',
          background: 'radial-gradient(closest-side, rgba(252,252,252,.78) 0%, rgba(252,252,252,.62) 45%, rgba(252,252,252,.28) 72%, rgba(252,252,252,0) 100%)',
          opacity: scrimOn,
          transform: `translateZ(${-80 * u}px)`,
        }}
      />
    ) : null;

  // ---- eyebrow, total, caption (flat, in front)
  const ui: React.ReactNode[] = [];
  const uiAt = (sx: number, sy: number, alpha: number, key: string, node: React.ReactNode, lift = 0) => {
    const z = 110 * u;
    const pl = place(g, sx, sy, z);
    ui.push(
      <div
        key={key}
        style={{
          position: 'absolute',
          left: pl.x,
          top: pl.y,
          opacity: alpha,
          transform: `translate(-50%, -50%) translateY(${lift}px) translateZ(${z}px) scale(${pl.k})`,
        }}
      >
        {node}
      </div>,
    );
  };
  const eb = enter(f, fps, 0, 14);
  const panel: React.CSSProperties = {
    background: COLORS.white,
    borderStyle: 'solid',
    borderWidth: 2 * u,
    borderColor: CARD_EDGE.borderColor,
    boxShadow: `0 ${3 * u}px 0 -${u}px #DCDCE1, 0 ${12 * u}px ${26 * u}px rgba(10,10,10,.09)`,
  };
  uiAt(
    g.W / 2,
    g.eyebrowY,
    eb,
    'eyebrow',
    <div style={{zoom: g.eyebrowZoom} as React.CSSProperties}>
      <div
        style={{
          background: COLORS.white,
          border: '2px solid',
          borderColor: CARD_EDGE.borderColor,
          boxShadow: '0 3px 0 -1px #DCDCE1, 0 12px 26px rgba(10,10,10,.09)',
          borderRadius: 999,
          padding: '12px 26px',
        }}
      >
        <Eyebrow text={eyebrow} progress={1} />
      </div>
    </div>,
    (1 - eb) * 14 * u,
  );
  const cap = enter(f, fps, 6, 14);
  const counter = <DollarCounter value={FINAL} f={1 - Math.cbrt(1 - y)} start={0} end={1} size={wide ? 116 : 62} color={COLORS.ink} />;
  if (!wide) {
    // Bottom block: the total, then the caption.
    if (showTotal) {
      uiAt(
        540,
        1150,
        cap,
        'total',
        <div style={{...panel, borderRadius: 26, padding: '8px 26px 8px 20px', display: 'flex', alignItems: 'center', gap: 14, whiteSpace: 'nowrap'}}>
          {counter}
          <span style={{fontSize: 27, fontWeight: 600, letterSpacing: TRACK.body, color: COLORS.gray, lineHeight: 1.1}}>
            in approvals
            <br />
            on screen
          </span>
        </div>,
      );
    }
    uiAt(
      540,
      showTotal ? 1210 : 1170,
      cap,
      'caption',
      <div style={{display: 'flex', alignItems: 'center', gap: 10, whiteSpace: 'nowrap', ...(showTotal ? {} : {...panel, borderRadius: 999, padding: '10px 24px'})}}>
        <Check size={showTotal ? 26 : 40} />
        <span style={{fontSize: showTotal ? 28 : 44, fontWeight: 700, letterSpacing: TRACK.h2, color: COLORS.ink}}>{caption}</span>
      </div>,
    );
  } else {
    // Right column: the total over the caption.
    uiAt(
      3190,
      1080,
      cap,
      'total',
      <div style={{...panel, borderRadius: 48, padding: '44px 56px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 18, whiteSpace: 'nowrap'}}>
        {showTotal ? (
          <>
            <span style={{fontSize: 46, fontWeight: 600, letterSpacing: TRACK.eyebrow, textTransform: 'uppercase', color: COLORS.gray}}>On screen</span>
            {counter}
            <span style={{fontSize: 50, fontWeight: 600, letterSpacing: TRACK.body, color: COLORS.gray}}>in approvals</span>
            <span style={{width: 520, height: 3, background: COLORS.line, margin: '8px 0'}} />
          </>
        ) : null}
        <span style={{display: 'flex', alignItems: 'center', gap: 20}}>
          <Check size={64} />
          <span style={{fontSize: 66, fontWeight: 700, letterSpacing: TRACK.h2, color: COLORS.ink}}>{caption}</span>
        </span>
      </div>,
    );
  }

  // ---- money on the stage: bills hanging over the pile, and a burst out from behind each slammed card
  const band: [number, number] = wide ? [0, g.H] : [269, 1248];
  const stageMoney: Piece[] = driftPieces(g, f, 'proof-flood-drift', wide ? 16 : 9, band[0] + 60, band[1] - 60);
  for (const sl of slams) {
    const pair = sl.beat.cards.length > 1;
    const box = pair ? g.hero2[sl.k] : g.hero1;
    stageMoney.push(...burstPieces(g, f, sl.at, box.x, box.y, box.w, box.h, `proof-flood-burst-${sl.beat.cards[sl.k].id}`, sl.last ? 30 : pair ? 14 : 22, sl.last ? 1.2 : 1));
  }

  return (
    <div
      style={{
        position: 'absolute',
        left: 0,
        top: 0,
        width: g.W,
        height: g.H,
        perspective: g.P,
        perspectiveOrigin: `${g.ox}px ${g.oy}px`,
      }}
    >
      <div style={{position: 'absolute', inset: 0, ...P3D, transformOrigin: `${g.ox}px ${g.oy}px`, transform: camT}}>
        {pile}
        <Decor>
          <MoneyPieces pieces={stageMoney} P={g.P} ox={g.ox} oy={g.oy} band={band} />
        </Decor>
        {scrim}
        {heroes}
        {ui}
        {pills}
        {chips}
      </div>
    </div>
  );
};

/** Decoration in front of the cards: the slam flashes, the money bursts and a few bills drifting down the sides. */
const FrontDecor: React.FC<{g: Geo; f: number; plan: ReturnType<typeof buildPlan>}> = ({g, f, plan}) => {
  const {u} = g;
  const pieces: Piece[] = [];
  const flashes: React.ReactNode[] = [];
  pieces.push(...rainPieces(g, f, 'proof-flood-front', g.gutters.count, [80, 380], 0.6, g.gutters.bands));
  plan.beats.forEach((b) => {
    const pair = b.cards.length > 1;
    b.cards.forEach((a, k) => {
      const at = b.s + k * PAIR_GAP;
      const box = pair ? g.hero2[k] : g.hero1;
      const last = b.last && k === b.cards.length - 1;
      const age = f - at;
      if (age < -2 || age > 16) return;
      const peak = last ? 0.9 : pair && k === 1 ? 0.55 : 0.82;
      const a1 = peak * (age < 0 ? clamp01(1 + age / 2) : Math.exp(-age / 3.2));
      const R = (pair ? 900 : 1150) * u;
      flashes.push(
        <AbsoluteFill
          key={`flash-${a.id}`}
          style={{
            background: `radial-gradient(circle at ${box.x}px ${box.y}px, rgba(255,255,255,${(0.95 * a1).toFixed(3)}) 0px, rgba(255,255,255,${(0.7 * a1).toFixed(3)}) ${R * 0.4}px, rgba(255,255,255,0) ${R}px)`,
          }}
        />,
      );
      if (age >= 0) {
        const rings = last ? [0, 4] : [0];
        rings.forEach((delay) => {
          const t = clamp01((age - delay) / 12);
          if (t <= 0 || t >= 1) return;
          const rad = (110 + (last ? 680 : 520) * easeOut(t)) * u;
          flashes.push(
            <div
              key={`ring-${a.id}-${delay}`}
              style={{
                position: 'absolute',
                left: box.x - rad,
                top: box.y - rad,
                width: rad * 2,
                height: rad * 2,
                borderRadius: '50%',
                border: `${(7 - 5 * t) * u}px solid rgba(61,134,240,${(0.5 * (1 - t) ** 2).toFixed(3)})`,
                boxShadow: `0 0 ${30 * u}px rgba(61,134,240,${(0.25 * (1 - t)).toFixed(3)})`,
              }}
            />,
          );
        });
      }
    });
  });
  const P = g.u > 1 ? DEPTH.backdropPerspective * 2 : DEPTH.backdropPerspective;
  const money = <MoneyPieces pieces={pieces} P={P} ox={g.ox} oy={g.oy} />;
  return (
    <>
      {g.u > 1 ? (
        <Decor>
          <AbsoluteFill style={{perspective: P, perspectiveOrigin: `${g.ox}px ${g.oy}px`}}>
            <div style={{position: 'absolute', inset: 0, ...P3D}}>{money}</div>
          </AbsoluteFill>
        </Decor>
      ) : (
        <BackdropStage f={f} length={PROOF_FLOOD_BASE} drift={0.7}>
          {money}
        </BackdropStage>
      )}
      <Decor>
        <AbsoluteFill style={{pointerEvents: 'none'}}>{flashes}</AbsoluteFill>
      </Decor>
    </>
  );
};

/** Money rain far behind the cards. */
const BackRain: React.FC<{g: Geo; f: number}> = ({g, f}) => {
  const P = g.u > 1 ? DEPTH.backdropPerspective * 2 : DEPTH.backdropPerspective;
  const money = <MoneyPieces pieces={rainPieces(g, f, 'proof-flood-rain', g.rain, [-950, -300], 0.5)} P={P} ox={g.ox} oy={g.oy} />;
  return g.u > 1 ? (
    <Decor>
      <AbsoluteFill style={{perspective: P, perspectiveOrigin: `${g.ox}px ${g.oy}px`}}>
        <div style={{position: 'absolute', inset: 0, ...P3D}}>{money}</div>
      </AbsoluteFill>
    </Decor>
  ) : (
    <BackdropStage f={f} length={PROOF_FLOOD_BASE} drift={0.7}>
      {money}
    </BackdropStage>
  );
};

export const ProofFlood: React.FC<ProofFloodProps> = (props) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const wide = props.format === 'wide';
  const g = wide ? WIDE : VERT;
  const f = (frame * PROOF_FLOOD_BASE) / clampProofFlood(props.durationInFrames);
  const {approvals, headline, format} = props;
  const plan = React.useMemo(() => buildPlan({...proofFloodDefaults, approvals, headline, format}, g), [approvals, headline, format, g]);
  const scene = <ProofFloodScene {...props} g={g} f={f} fps={fps} plan={plan} />;

  if (!wide) {
    // BrandFrame clips the words to the text-safe band (y 269 to 1248). Its content box starts at
    // (90, 400); the scene is laid out in full-frame pixels, so it is shifted back by that much.
    return (
      <AbsoluteFill>
        <BrandFrame showSafeZones={props.showSafeZones} backdrop={<BackRain g={g} f={f} />}>
          <div style={{position: 'absolute', left: -90, top: -400, width: g.W, height: g.H}}>{scene}</div>
        </BrandFrame>
        <FrontDecor g={g} f={f} plan={plan} />
      </AbsoluteFill>
    );
  }

  // Wide: same brand page (paper, faint grid at the 4K scale, wordmark), words inside a 5% title-safe margin.
  const line = 3;
  return (
    <AbsoluteFill style={{fontFamily: FONT_FAMILY, color: COLORS.ink, WebkitFontSmoothing: 'antialiased'}}>
      <AbsoluteFill
        style={{
          backgroundColor: COLORS.paper,
          backgroundImage: `linear-gradient(${GRID.color} ${line}px, transparent ${line}px), linear-gradient(90deg, ${GRID.color} ${line}px, transparent ${line}px)`,
          backgroundSize: `${GRID.cell}px ${GRID.cell}px`,
          backgroundPosition: `${-line / 2}px ${-line / 2}px`,
        }}
      />
      <BackRain g={g} f={f} />
      {scene}
      <div style={{position: 'absolute', left: 0, right: 0, top: 150, display: 'flex', justifyContent: 'center'}}>
        <Wordmark width={380} />
      </div>
      <FrontDecor g={g} f={f} plan={plan} />
      {props.showSafeZones ? (
        <AbsoluteFill style={{pointerEvents: 'none'}}>
          <div style={{position: 'absolute', left: g.W * 0.05, top: g.H * 0.05, right: g.W * 0.05, bottom: g.H * 0.05, border: '6px solid #DC2626'}} />
        </AbsoluteFill>
      ) : null}
    </AbsoluteFill>
  );
};

const sizeFor = (format: ProofFloodFormat | undefined) => (format === 'wide' ? {width: WIDE.W, height: WIDE.H} : {width: VERT.W, height: VERT.H});

/** Registered in Root.tsx: ProofFlood (vertical, ads) and ProofFloodWide (4K, the horizontal VSL). */
export const ProofFloodCompositions: React.FC = () => (
  <>
    <Composition
      id="ProofFlood"
      component={ProofFlood}
      durationInFrames={PROOF_FLOOD_BASE}
      fps={FRAME.fps}
      width={VERT.W}
      height={VERT.H}
      defaultProps={proofFloodDefaults}
      calculateMetadata={({props}) => ({durationInFrames: clampProofFlood(props.durationInFrames), ...sizeFor(props.format)})}
    />
    <Composition
      id="ProofFloodWide"
      component={ProofFlood}
      durationInFrames={PROOF_FLOOD_BASE}
      fps={FRAME.fps}
      width={WIDE.W}
      height={WIDE.H}
      defaultProps={{...proofFloodDefaults, format: 'wide'}}
      calculateMetadata={({props}) => ({durationInFrames: clampProofFlood(props.durationInFrames), ...sizeFor(props.format)})}
    />
  </>
);
