// GENERATED by marketing/broll/scripts/proof-flood-approvals.py. Do not edit by hand.
// 46 real approvals, smallest first. Pictures in public/proof-flood/<id>.jpg.
// `amount`, `lender` and `product` come from deck.json or approvals-manifest.json (read off each
// picture); `lender` is null when the picture names no lender. `source` says where each figure is read.
// Sum of every amount: 2391400 (the running total when all of them are on screen).

export type FloodApproval = {
  id: string;
  width: number;
  height: number;
  amount: number;
  lender: string | null;
  product: string | null;
  source: string;
};

export const FLOOD_APPROVALS: FloodApproval[] = [
  {id: "win-5000-nihfcu", width: 964, height: 507, amount: 5000, lender: "NIHFCU", product: null, source: "approvals-manifest.json win-5000-nihfcu: reads 'approved me for $5k!' -> 5000"},
  {id: "u-6000-jetblue", width: 1200, height: 900, amount: 6000, lender: "Barclays (JetBlue)", product: "JetBlue World Mastercard", source: "deck.json u-6000-jetblue: revolving credit line of $6,000.00"},
  {id: "u-6500-discover", width: 1200, height: 900, amount: 6500, lender: "Discover", product: "Discover it card", source: "deck.json u-6500-discover: Your credit line is $6,500."},
  {id: "win-7000-citizens", width: 964, height: 1229, amount: 7000, lender: "Citizens", product: "Everyday Points Business MasterCard", source: "approvals-manifest.json win-7000-citizens: reads '$7,000.00' in green under 'Everyday Points Business MasterCard' in the Citizens approval email attached inside the text thread"},
  {id: "win-7500-pnc", width: 964, height: 177, amount: 7500, lender: "PNC", product: "Business credit card", source: "approvals-manifest.json win-7500-pnc: reads '7.5k' -> 7500"},
  {id: "u-8300-chase-freedom-unlimited", width: 1200, height: 900, amount: 8300, lender: "Chase", product: "Chase Freedom Unlimited", source: "deck.json u-8300-chase-freedom-unlimited: Your credit line is $8,300.00"},
  {id: "u-8800-chase-freedom-unlimited", width: 1200, height: 900, amount: 8800, lender: "Chase", product: "Chase Freedom Unlimited", source: "deck.json u-8800-chase-freedom-unlimited: Your credit line is $8,800.00"},
  {id: "win-9000-southstate", width: 964, height: 1313, amount: 9000, lender: "SouthState", product: "Visa Business Card", source: "approvals-manifest.json win-9000-southstate: reads 'CREDIT LIMIT: $9000' on the SouthState card-carrier line"},
  {id: "u-10k-citizens", width: 1200, height: 900, amount: 10000, lender: "Citizens Bank", product: "Everyday Points Business MasterCard", source: "deck.json u-10k-citizens: Everyday Points Business MasterCard $10,000.00"},
  {id: "u-10k-jetblue", width: 1200, height: 900, amount: 10000, lender: "Barclays (JetBlue)", product: "JetBlue World Mastercard", source: "deck.json u-10k-jetblue: revolving credit line of $10,000.00"},
  {id: "u-10k-sofi", width: 1200, height: 900, amount: 10000, lender: "SoFi", product: "SoFi World Elite Mastercard", source: "deck.json u-10k-sofi: Credit Line $10,000"},
  {id: "u-10k-usaa", width: 1200, height: 900, amount: 10000, lender: "USAA", product: "USAA Rate Advantage Visa Platinum", source: "deck.json u-10k-usaa: Credit Limit $10,000.00"},
  {id: "win-10000-u-s-bank", width: 964, height: 1355, amount: 10000, lender: "U.S. Bank", product: "Credit card", source: "approvals-manifest.json win-10000-u-s-bank: reads 'that will give you a total credit line of $10,000.'"},
  {id: "u-10700-chase-freedom", width: 1200, height: 900, amount: 10700, lender: "Chase", product: "Chase Freedom Unlimited", source: "deck.json u-10700-chase-freedom: Credit line: $10,700.00"},
  {id: "u-12k-discover", width: 1200, height: 900, amount: 12000, lender: "Discover", product: "Discover it Business card", source: "deck.json u-12k-discover: Your credit line is $12,000."},
  {id: "win-12000-bank-of-america-2", width: 964, height: 671, amount: 12000, lender: "Bank of America", product: "Business credit card", source: "approvals-manifest.json win-12000-bank-of-america-2: reads 'you'll have $12,000 of available credit' in the Bank of America approval email attached inside the text thread. The '24K' in the bubbles is the client's running total across banks, and it is what the yellow number copies - it is NOT this approval's amount"},
  {id: "u-13800-chase-freedom", width: 1200, height: 900, amount: 13800, lender: "Chase", product: "Chase Freedom", source: "deck.json u-13800-chase-freedom: Your credit line is $13,800.00"},
  {id: "u-14k-fnbo", width: 1200, height: 900, amount: 14000, lender: "FNBO", product: "Signature Visa", source: "deck.json u-14k-fnbo: Approved Credit Limit: $14,000"},
  {id: "u-15k-pnc", width: 1200, height: 900, amount: 15000, lender: "PNC Bank", product: "PNC Core Visa", source: "deck.json u-15k-pnc: Application Approved ... Credit Limit $15,000"},
  {id: "win-15000-fnbo", width: 964, height: 477, amount: 15000, lender: "FNBO", product: "0% business credit", source: "approvals-manifest.json win-15000-fnbo: reads 'Just got approved for $15,000 0% business credit at FNBO' in the message bubble"},
  {id: "win-16000-bankunited", width: 964, height: 687, amount: 16000, lender: "BankUnited", product: null, source: "approvals-manifest.json win-16000-bankunited: reads 'Your credit line is $16,000.'"},
  {id: "g-20k-instant", width: 1200, height: 900, amount: 20000, lender: null, product: "Credit card", source: "deck.json g-20k-instant: Instant Approved ... Credit Limit $20,000.00"},
  {id: "t-20k-truist", width: 1200, height: 900, amount: 20000, lender: "Truist", product: "Business credit card", source: "deck.json t-20k-truist: Credit limit: $20,000"},
  {id: "g-20500k-visa-platinum", width: 1200, height: 900, amount: 20500, lender: null, product: "Visa Platinum card", source: "deck.json g-20500k-visa-platinum: accepted and approved ... Credit Limit $20,500.00"},
  {id: "d-23k-chase-freedom", width: 1200, height: 900, amount: 23000, lender: "Chase", product: "Freedom Unlimited card", source: "deck.json d-23k-chase-freedom: Your credit line is $23,000.00"},
  {id: "d-24k-navy", width: 1200, height: 900, amount: 24000, lender: "Navy Federal Credit Union", product: "Platinum Visa credit card", source: "deck.json d-24k-navy: You've been approved for a Platinum Credit Card with a credit limit of $24000.00. Your APR is 7.99%."},
  {id: "d-25k-personal-card", width: 1200, height: 900, amount: 25000, lender: "Navy Federal Credit Union", product: "cashRewards Visa credit card", source: "deck.json d-25k-personal-card: Your Credit Limit $ 25,000.00"},
  {id: "t-25k-highland", width: 1200, height: 900, amount: 25000, lender: "Highland Bank", product: "Visa Business Card", source: "deck.json t-25k-highland: Your credit line: $25,000.00"},
  {id: "win-25000-enterprise-bank-trust", width: 964, height: 1355, amount: 25000, lender: "Enterprise Bank & Trust", product: null, source: "approvals-manifest.json win-25000-enterprise-bank-trust: reads 'CREDIT LIMIT: $25,000' on the hand-circled line of the mailed card carrier; last digit is soft at this resolution but the figure is $25,000"},
  {id: "win-25000-umpqua-bank", width: 964, height: 937, amount: 25000, lender: "Umpqua Bank", product: "Visa Business Card", source: "approvals-manifest.json win-25000-umpqua-bank: reads 'Your credit line is $25,000.'"},
  {id: "d-30k-navy", width: 1200, height: 900, amount: 30000, lender: "Navy Federal", product: "Platinum credit card", source: "deck.json d-30k-navy: Your Credit Limit $30,000.00"},
  {id: "g-30k-first-tech", width: 1200, height: 900, amount: 30000, lender: "First Tech", product: "Choice Rewards World MasterCard", source: "deck.json g-30k-first-tech: Credit Limit: $30,000.00"},
  {id: "g-30k-service-cu", width: 1200, height: 900, amount: 30000, lender: "Service Credit Union", product: "Visa Everyday Elite Signature", source: "deck.json g-30k-service-cu: approved for a Visa Everyday Elite Signature ... with a credit limit of $30,000.00"},
  {id: "g-35k-first-tech-a", width: 1200, height: 900, amount: 35000, lender: "First Tech", product: "Choice Rewards World MasterCard", source: "deck.json g-35k-first-tech-a: Credit Limit: $35,000.00"},
  {id: "g-35k-first-tech-b", width: 1200, height: 900, amount: 35000, lender: "First Tech", product: "Choice Rewards World MasterCard", source: "deck.json g-35k-first-tech-b: Credit Limit: $35,000.00"},
  {id: "d-41k-chase-ink", width: 1200, height: 900, amount: 41000, lender: "Chase", product: "Ink Business Unlimited card", source: "deck.json d-41k-chase-ink: Credit line: $41,000.00"},
  {id: "g-48k-elan", width: 1200, height: 900, amount: 48000, lender: "Elan Financial Services", product: "Visa Business Card", source: "deck.json g-48k-elan: Your credit line is $48,000."},
  {id: "keybank-50k-loc", width: 964, height: 961, amount: 50000, lender: "KeyBank", product: "Business line of credit", source: "Canva Client Wins deck page 37 (KeyBank), screenshot inside proof-wall/win-noamount-keybank-p37-1.png; amount from the picture's caption '$50k Business Line Of Credit Approval' and deck page 37; the screen itself shows $49,764.00 available balance"},
  {id: "t-50k-chase", width: 1200, height: 900, amount: 50000, lender: "Chase", product: "Ink Business card", source: "deck.json t-50k-chase: Total credit limit $50,000.00 (also Available credit $50,000.00)"},
  {id: "t-50k-keybank", width: 1200, height: 900, amount: 50000, lender: "KeyBank", product: "KeyBank Business Cash Rewards card", source: "deck.json t-50k-keybank: Credit Limi[t:] 50000 (the owner's blue circle covers the 't:', same as in the original)"},
  {id: "d-54k-ink", width: 1200, height: 900, amount: 54500, lender: "Chase", product: "Ink Business Unlimited card", source: "deck.json d-54k-ink: Credit Access Line†: $54,500"},
  {id: "d-70k-loc", width: 1200, height: 900, amount: 70000, lender: null, product: "Business Revolving Line of Credit", source: "deck.json d-70k-loc: $70,000.00"},
  {id: "t-74k-chase-ink", width: 1200, height: 900, amount: 74000, lender: "Chase", product: "Ink Business Cash card", source: "deck.json t-74k-chase-ink: Your credit limit is $74,000."},
  {id: "d-400k-loc", width: 1200, height: 900, amount: 400000, lender: null, product: "Commercial line of credit", source: "deck.json d-400k-loc: Credit limit $400,000.00"},
  {id: "d-469k-loc", width: 1200, height: 900, amount: 469800, lender: null, product: "Commercial Line of Credit", source: "deck.json d-469k-loc: Credit limit $469,800.00"},
  {id: "d-500k-loc", width: 1200, height: 900, amount: 500000, lender: null, product: "Commercial Line of Credit", source: "deck.json d-500k-loc: Credit limit $500,000.00"},
];

export const FLOOD_TOTAL = 2391400;
